spring.application.name=ventas

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/ventas
spring.datasource.username=ventas
spring.datasource.password=ventas
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

springdoc.swagger-ui.path=/swagger-ui.html

management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.tags.application=ventas-api
management.prometheus.metrics.export.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true